### ISSUE TITLE
pid controller

### ISSUE THREAD

**Issue by Irisz10** [ni/nidaqmx-python#160]
Hi, I wanted to implement a PID loop for controlling the phase of the signal and I had nearly everything ready on DAQExpress, except my supervisor asked me to use Python because it is more adaptable. In fact, I have to insert a way to make the PID realize if a phase is negative or positive (because as the signal is projected on the "x axis" it sees phases close to zero all the same)... however the MOST IMPENDING QUESTION I have is: where can I find the PID CONTROLLER? 

How do you usually implement a PID on Python? It has to be quite fast in order to react to the changes of the signal in real time (that's also one of the difficulties of using nidaqmm python because you can't adjust as easily the sample rates and durations)

**Comment by zhindes** [comment]
This isn't a question specific to the DAQmx API or Python bindings and isn't appropriate as an issue. However, I'll give you some pointers as I close this.

> where can I find the PID CONTROLLER?

You need to find a library that implements a PID algorithm so you can input the measured response and calculate the new output. A quick google search turned up https://github.com/m-lundberg/simple-pid which looks reasonable, but I cannot vouch for its correctness or if it will meet your needs.

> It has to be quite fast in order to react to the changes of the signal in real time (that's also one of the difficulties of using nidaqmm python because you can't adjust as easily the sample rates and durations)

How fast it needs to be is a function of your application. You need to determine that. However, if it does need to be fast, DAQmx provides the [Hardware-Timed Single Point](https://www.ni.com/documentation/en/ni-daqmx/20.1/mxcncpts/hwtspsamplemode/) sample mode for those applications. It is designed for applications that need fast single-point control. Because of this it is only implemented on certain devices and bus architectures (PCI/PCIe and not USB/Ethernet, for example). It is also optimized for Real-Time Operating Systems such as NI Linux RT. It is available on Windows, but has lower performance.
