### ISSUE TITLE
Stagnant Corresponding Measurements After First Acquisition

### ISSUE THREAD

**Issue by JiaLim98** [ni/nidaqmx-python#178]
Hi,

I am currently using USB-6211 for voltage measurement acquisition. I have configured it using the following codes:

`task.ai_channels.add_ai_voltage_chan("Dev1/ai0", terminal_config=nidaqmx.constants.TerminalConfiguration.RSE, min_val=-10.0, max_val=10.0, units=nidaqmx.constants.VoltageUnits.VOLTS)`
`task.timing.cfg_samp_clk_timing(250000, active_edge=nidaqmx.constants.Edge.RISING, sample_mode=nidaqmx.constants.AcquisitionType.CONTINUOUS, samps_per_chan=10**6)`

I have no issue in getting the fast acquisition rate, but the values I am getting are wrong. The subsequent measurements always follow the first measurement value. For example, the figure below shows the measurements collected under the same application with USB-6001 and USB-6211.

<img width="492" alt="image" src="https://user-images.githubusercontent.com/66768413/174790614-ba6dccca-ab74-4513-9d48-6eb2c4f219f0.png">

The measurements collected using USB-6001 are what I am looking for. Anyone knows the cause or know the solution for this issue? I am suspecting the buffer size to be the reason, but going any lower will cause `The application is not able to keep up with the hardware acquisition.` and nidaqmx asks to increase the buffer size. Thanks in advance.

**Comment by zhindes** [comment]
A few things:

* How do you know the values are wrong? That looks like floating or maybe even grounded data to me. 6001/6211 data seems similar enough. I would recommend using a test panel in NI-MAX to validate your connections, first.
* You're not actually setting the buffer size in your code. [DAQmx determines a default buffer size based on your samples per channel](https://knowledge.ni.com/KnowledgeArticleDetails?id=kA00Z000000P9PkSAK&l=en-US). If you want, you can set it explicitly with [in_stream.input_buf_size](https://nidaqmx-python.readthedocs.io/en/latest/in_stream.html#nidaqmx._task_modules.in_stream.InStream.input_buf_size).
* Buffer size is likely not your issue, its likely your read size with a relatively low rate like 250khz. Ensure your application can keep up with the data by reading a big enough data set. A decent rule of thumb is 10 reads per second. Consider using a [stream_reader](https://nidaqmx-python.readthedocs.io/en/latest/stream_readers.html) for optimized reads in Python. [pwr_hw_timed_stream.py](https://github.com/ni/nidaqmx-python/blob/master/nidaqmx_examples/pwr_hw_timed_stream.py) demonstrates that; simply update it to use voltage instead.

All that being said, I don't believe this is an issue with DAQmx Python binding. I am closing this. If you have reason to believe otherwise, feel free to reopen the issue. I recommend the [Multifunction DAQ forum @ ni.com](https://forums.ni.com/t5/Multifunction-DAQ/bd-p/250) for general debugging using an NI DAQ device and NI-DAQmx.
