### ISSUE TITLE
Conflict with nidaqmx and threads

### ISSUE THREAD

**Issue by Ton1Berger** [ni/nidaqmx-python#213]
So I noticed, that whenever nidaqmx is imported in my python script (Anaconda environment, python version 3.9.16, nidaqmx version 0.6.5), all threads opened in the main script end with a ResourceWarning:

sys:1: ResourceWarning: unclosed socket <zmq.Socket(zmq.PUSH) at 0x1c364caae80>
ResourceWarning: Enable tracemalloc to get the object allocation traceback

A minimal reproducible example:

```
import nidaqmx
import threading
import any_function

my_thread = threading.Thread(target=any_function)
my_thread.start()
```

I could just ignore the warning, however, I noticed that after repeatedly opening and closing threads with this error message results in the Kernel dying and restarting.

Any help would be much appreciated!

**Comment by zhindes** [comment]
I can't reproduce this, and I don't think its related to `nidaqmx`. `zmq` is ZeroMQ, which `nidaqmx` has no dependency per the [poetry.lock](https://github.com/ni/nidaqmx-python/blob/master/poetry.lock). I found a similar report on Stack Overflow [[asfd](sys:1: ResourceWarning: unclosed socket <zmq.Socket(zmq.PUSH) at 0x7f8a5c016d60>)[sys:1: ResourceWarning: unclosed socket <zmq.Socket(zmq.PUSH) at 0x7f8a5c016d60>](https://stackoverflow.com/questions/71331789/sys1-resourcewarning-unclosed-socket-zmq-socketzmq-push-at-0x7f8a5c016d60)](https://stackoverflow.com/questions/71331789/sys1-resourcewarning-unclosed-socket-zmq-socketzmq-push-at-0x7f8a5c016d60) that indicates it is likely due to Spyder. It appears that Anaconda has Spyder available by default per [their website](https://www.anaconda.com/products/distribution). Perhaps there is a newer version of either Anaconda or Spyder?
