### ISSUE TITLE
Differences with PyDAQmx ?

### ISSUE THREAD

**Issue by MaxP92** [ni/nidaqmx-python#41]
Hello,

What are the differences with PyDAQmx ?
[pythonhosted.org/PyDAQmx/](https://pythonhosted.org/PyDAQmx)

Is there something in this package that PyDAQmx does not have ?

Or are the performances improved ?

Which one should I use ?

Thanks!

**Comment by neilvana** [comment]
PyDAQmx was developed in the community before NI developed an official Python API.  While PyDAQmx provided a path for Python users to access NI Data Acquisition for several years, we felt we could add value by providing a more pythonic api with more complete documentation, optional parameters and a focus on ease of use.  There are a few notable differences:

- nidaqmx has more significant API documentation for attributes and methods
- nidaqmx methods have reasonable default values for many parameters which are optional
- nidaqmx is static rather than dynamically generated at runtime allowing easier inspection of the API
- nidaqmx is the official National Instruments supported API

In many respects PyDAQmx has been a pretty shallow wrapper over the NI-DAQmx C API.  nidaqmx is focused on being more pythonic and providing a more natural experience and better ade support for Python developers.
