### ISSUE TITLE
try to set voltage higher than specified

### ISSUE THREAD

**Issue by Jo-Blade** [ni/nidaqmx-python#423]
I am trying to write data to the ao0 output of my NI USB-6009. This output accept voltage from 0 to 5V.

The issue is exactly the same as #29 but it was closed years ago without solution.

I am on windows 11, python 3.11 from the windows store and latest pip version of nidaqmx

**Comment by zhindes** [comment]
Even if your issue is "exactly the same" as another, it is useful to output the exact error message you are seeing. Often times you might think something is the same, but it isn't.

Anyways, my psychic debugging tells me, that you aren't specifying the `min_val` and `max_val` optional parameters on `add_ao_voltage_chan`. As you mentioned the 6009 Analog Output is unipolar 0-5V. The default values for min and max are -10 and 10, respectively. Therefore, if you don't specify them you should expect an error.

Simply pass values for min and max here:

```python
with nidaqmx.Task() as task:
    task.ao_channels.add_ao_voltage_chan("6009/ao0", min_val=0.0, max_val=5.0)
```

**Comment by Jo-Blade** [comment]
Thank you very much, I have in fact missed this optional argument. I think it should be the problem. I will try tomorrow when I'll have my computer back. Sorry for the inconvenience.
