### ISSUE TITLE
Interfacing with real time controller

### ISSUE THREAD

**Issue by afrozaky** [ni/nidaqmx-python#441]
Hi, 

Sorry if this is not the appropriate place to ask, but I placed a question on the NI forums as well. 
    I have a cDAQ-9132 system with a counter module and strain gauge module. Currently the cDAQ-9132 system runs a VI that samples one channel from the counter module and one channel from the strain gauge module and creates two shared variables. A desktop PC connected to the cDAQ-9132, runs a VI for an operator graphical-user-interface, and sees the shared variables to present the data in a live graph. 
   I would like to convert the entire system to Python (both the desktop PC and the cDAQ-9132). I have been reviewing the official NI Python DAQmx library and I believe it could fit my needs; however, I am confused as to which devices are supported. Basically, I would like to sample the cDAQ-9132 as if it was a regular DAQ from a Python script running on the desktop PC through the NI Python DAQmx library similar to [this example](https://forums.ni.com/t5/Example-Code/Python-Voltage-Continuous-Input-py/ta-p/3938650). Is this possible? I have simulated the DAQ and tested this ability and it seems to work properly; however, I want to make sure my understanding is correct. I cannot test on the actual system currently as there is not any machine downtime for a few weeks.
   Currently, I have NI MAX 18.5 installed on the desktop PC as well as the cDAQ. I am using Python 3.11.2 and NI-DAQmx Python package version 0.7.0. Please see a full configuration below. Any advice or suggestions would be greatly appreciated.

Configuration:

cDAQ-9132 with NI MAX 18.5
NI 9361 C Series Counter Input Module
NI 9237 C Series Strain/Bridge Input Module
Desktop PC with Windows 10, and NI MAX 18.5

**Comment by zhindes** [comment]
The cDAQ-9132 is a standalone controller. It sounds like yours is running NI Linux RT, but some variants run Windows. Regardless, the flow is the same - the NI-DAQmx driver is installed on the target, and any software you write that interacts with IO via NI-DAQmx must be running on the target. So, no, by default, there is no way to have NI-DAQmx on your Windows host PC interact with IO on the target.

That being said, [NI gRPC Device Server and Client APIs](https://github.com/ni/grpc-device/) allows you to do this. In this situation the NI gRPC Device Server is running on your cDAQ-9132. It is executing NI-DAQmx driver functionality on the target on behalf of any clients from other systems (or local processes). There are [examples](https://github.com/ni/grpc-device/tree/main/examples/nidaqmx) that demonstrate how a client would interface that using gRPC directly, rather than through the `nidaqmx` bindings. You could also use something like [RPyC](https://rpyc.readthedocs.io/en/latest/) to leverage the `nidaqmx` bindings remotely on another system.
